##services:
##  gateway:
##    build: shareit-gateway
##    image: shareit-gateway
##    container_name: shareit-gateway
##    ports:
##      - "8080:8080"
##    depends_on:
##      - server
##    environment:
##      - SHAREIT_SERVER_URL=http://server:9090
##
##  server:
##      build: shareit-server
##      image: shareit-server
##      container_name: shareit-server
##      ports:
##        - "9090:9090"
##      depends_on:
##        - db
##      environment:
##        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
##        - SPRING_DATASOURCE_USERNAME=shareit
##        - SPRING_DATASOURCE_PASSWORD=shareit
##
##  db:
##    image: postgres:16.1
##    container_name: postgres
##    ports:
##      - "5432:5432"
##    volumes:
##      - ./db/postgres:/var/lib/postgresql/data/
##    environment:
##      - POSTGRES_DB=shareit
##      - POSTGRES_USER=shareit
##      - POSTGRES_PASSWORD=shareit
##    healthcheck:
##      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
##      timeout: 5s
##      interval: 5s
##      retries: 10
##
##  db-init:
##    image: postgres:16.1
##    container_name: db-init
##    depends_on:
##      db:
##        condition: service_healthy
##    entrypoint:
##      - bash
##      - -c
##      - |
##        set -e
##        psql postgresql://dbuser:12345@db:5432/shareit -v ON_ERROR_STOP=1 <<-EOSQL
##        CREATE TABLE IF NOT EXISTS users (
##          user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
##          name VARCHAR(40),
##          email VARCHAR(255)
##        );
##
##        CREATE TABLE IF NOT EXISTS booking_status (
##          id INT PRIMARY KEY,
##          name VARCHAR(40) NOT NULL
##        );
##
##        CREATE TABLE IF NOT EXISTS item_requests (
##          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
##          description VARCHAR(255) NOT NULL,
##          user_id INTEGER REFERENCES users ON DELETE CASCADE,
##          created TIMESTAMP WITHOUT TIME ZONE
##        );
##
##        CREATE TABLE IF NOT EXISTS items (
##          item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
##          name VARCHAR(40),
##          description VARCHAR(255),
##          available BOOLEAN,
##          owner_id INTEGER REFERENCES users ON DELETE CASCADE,
##          request_id INTEGER REFERENCES item_requests ON DELETE CASCADE
##        );
##
##        CREATE TABLE IF NOT EXISTS booking (
##          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
##          start_date TIMESTAMP WITHOUT TIME ZONE,
##          end_date TIMESTAMP WITHOUT TIME ZONE,
##          item_id INTEGER REFERENCES items ON DELETE CASCADE,
##          booker_id INTEGER REFERENCES users ON DELETE CASCADE,
##          status varchar(50)
##        );
##
##        CREATE TABLE IF NOT EXISTS comments (
##          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
##          item_id INTEGER REFERENCES items ON DELETE CASCADE,
##          author_id INTEGER REFERENCES users ON DELETE CASCADE,
##          text VARCHAR(255),
##          created TIMESTAMP WITHOUT TIME ZONE
##        );
##
##        CREATE TABLE IF NOT EXISTS responses (
##          id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
##          item_id INTEGER REFERENCES items ON DELETE CASCADE,
##          request_id INTEGER REFERENCES item_requests ON DELETE CASCADE
##        );
##        EOSQL
#
#services:
#  server:
#    build:
#      context: ./shareit-server
#      dockerfile: Dockerfile
#    image: shareit-server
#    container_name: shareit-server
#    ports:
#      - "9090:9090"
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
#      SPRING_DATASOURCE_USERNAME: shareit
#      SPRING_DATASOURCE_PASSWORD: shareit
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#
#    gateway:
#      build:
#        context: ./shareit-gateway
#        dockerfile: Dockerfile
#      image: shareit-gateway
#      container_name: shareit-gateway
#      ports:
#        - "8080:8080"
#      depends_on:
#        server:
#          condition: service_started
#      environment:
#        SHAREIT_SERVER_URL: "http://server:9090"
#
#  volumes:
#    pg_data:
#
#  db:
#    image: postgres:16.1
#    container_name: postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pg_data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: shareit
#      POSTGRES_USER: shareit
#      POSTGRES_PASSWORD: shareit
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#
#  db-init:
#      image: postgres:16.1
#      depends_on:
#        db:
#          condition: service_healthy
#          environment:
#            PGPASSWORD: shareit
#          command: >
#            bash -c "
#            until psql -h db -U shareit -d shareit -c 'SELECT 1'; do sleep 1; done;
#            psql -h db -U shareit -d shareit -v ON_ERROR_STOP=1 <<-EOSQL
#              CREATE TABLE IF NOT EXISTS users (
#                user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
#                name VARCHAR(40),
#                email VARCHAR(255)
#              );
#
#              CREATE TABLE IF NOT EXISTS booking_status (
#                id INT PRIMARY KEY,
#                name VARCHAR(40) NOT NULL
#              );
#
#              CREATE TABLE IF NOT EXISTS item_requests (
#                id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
#                description VARCHAR(255) NOT NULL,
#                user_id INTEGER REFERENCES users ON DELETE CASCADE,
#                created TIMESTAMP WITHOUT TIME ZONE
#              );
#
#              CREATE TABLE IF NOT EXISTS items (
#                item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
#                name VARCHAR(40),
#                description VARCHAR(255),
#                available BOOLEAN,
#                owner_id INTEGER REFERENCES users ON DELETE CASCADE,
#                request_id INTEGER REFERENCES item_requests ON DELETE CASCADE
#              );
#
#              CREATE TABLE IF NOT EXISTS booking (
#                id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
#                start_date TIMESTAMP WITHOUT TIME ZONE,
#                end_date TIMESTAMP WITHOUT TIME ZONE,
#                item_id INTEGER REFERENCES items ON DELETE CASCADE,
#                booker_id INTEGER REFERENCES users ON DELETE CASCADE,
#                status varchar(50)
#              );
#
#              CREATE TABLE IF NOT EXISTS comments (
#                id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
#                item_id INTEGER REFERENCES items ON DELETE CASCADE,
#                author_id INTEGER REFERENCES users ON DELETE CASCADE,
#                text VARCHAR(255),
#                created TIMESTAMP WITHOUT TIME ZONE
#              );
#
#              CREATE TABLE IF NOT EXISTS responses (
#                id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
#                item_id INTEGER REFERENCES items ON DELETE CASCADE,
#                request_id INTEGER REFERENCES item_requests ON DELETE CASCADE
#              );
#              EOSQL
services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: shareit
      POSTGRES_PASSWORD: shareit
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit -d shareit"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build:
      context: ./shareit-server
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: shareit
      SPRING_DATASOURCE_PASSWORD: shareit
    depends_on:
      db:
        condition: service_healthy

  gateway:
    build:
      context: ./shareit-gateway
    ports:
      - "8080:8080"
    environment:
      SHAREIT_SERVER_URL: "http://server:9090"
    depends_on:
      server:
        condition: service_started

volumes:
  pg_data: