CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    email VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS booking_status (
    id INT PRIMARY KEY,
    name VARCHAR(40) NOT NULL
    );

CREATE TABLE IF NOT EXISTS item_request (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description VARCHAR(255) NOT NULL,
    user_id INTEGER REFERENCES users ON DELETE CASCADE,
    created DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS items (
    item_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available BOOLEAN DEFAULT FALSE,
    owner_id INTEGER REFERENCES users ON DELETE CASCADE,
    request_id INTEGER REFERENCES item_request ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS booking (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    start_day DATE NOT NULL,
    end_day DATE NOT NULL,
    item_id INTEGER REFERENCES items ON DELETE CASCADE,
    booker_id INTEGER REFERENCES users ON DELETE CASCADE,
    booking_status_id INTEGER REFERENCES booking_status ON DELETE SET NULL
    );